services:
  tfg:
    build: tfg
    ports:
      - 8102:80
    volumes:
      - ./../app:/var/www/html
    hostname: tfg
    container_name: tfg
  mysql:
    image: mysql
    ports:
      - 23306:3306
    environment:
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=lectio_db
    volumes:
      - mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8101:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysql: